import type { Metadata } from "next";
import { Montserrat, Sora } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import RecaptchaProvider from "./components/RecaptchaProvider";

const montserratSans = Montserrat({
	variable: "--font-montserrat-sans",
	subsets: ["latin"],
});

const soraSans = Sora({
	variable: "--font-sora-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Haiven",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${montserratSans.variable} ${soraSans.variable} antialiased`}
			>
				<RecaptchaProvider>
					<Navbar />
					{children}
					<Footer />
				</RecaptchaProvider>
			</body>
		</html>
	);
}
